POST http://localhost:5000/users/register
Content-Type: application/json

{
    "username": "johndoe",
    "password": "123",
    "email": "john@doefamily.com"
}

###

POST http://localhost:5000/users/login
Content-Type: application/json

{
    "username": "johndoe",
    "password": "123"
}

###

POST http://localhost:5000/reviews/ISBN/create
Content-Type: application/json
Authorization: INSERT_TOKEN

{
    "text": "Text" 
}

###

GET http://localhost:5000/reviews/ISBN/all

###
GET http://localhost:5000/search/1984