POST http://localhost:5000/api/users/register
Content-Type: application/json

{
    "username": "johndoe2",
    "password": "123",
    "email": "john4@doefamily.com"
}

###

POST http://localhost:5000/api/users/login
Content-Type: application/json

{
    "username": "johndoe",
    "password": "123"
}

###

POST http://localhost:5000/api/reviews/Z2ClDwAAQBAJ/create
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MzM1NDg0OTYsImlhdCI6MTYzMzU0NjY5Niwic3ViIjoiMSJ9.AgiXwe_tP_b8xQctVucFXR3qOy0cgerEa5f-BzyD8XA

{
    "text": "A very good book. I would rather read 1984 than this tho."
}

###

GET http://localhost:5000/api/reviews/Z2ClDwAAQBAJ/all

###
GET http://localhost:5000/api/search/1984

###

GET http://localhost:5000/api/reviews/user/1

###

GET http://localhost:5000/api/reviews/is_reviewed/Z2ClDwAAQBAJ/1